### ISSUE TITLE
 when i submit new workflow nothing happens.

### ISSUE THREAD

**Issue by nishit93-hub** [vfarcic/argo-events-demo#1]
Hi,

Can we submit a new workflow using Argo-events-sensor? I am able to re-submit the existing workflow but when I submit new workflow nothing happens. No new workflow was submitted when I check from Argo Workflow UI.

Below are the logs
```
Name:                ci-pipelinej62bx
Namespace:           argo-events
ServiceAccount:      default
Status:              Pending
Created:             Tue Jan 11 08:41:01 +0000 (now)
Progress:            

This workflow does not have security context set. You can run your workflow pods more securely by setting it.
Learn more at https://argoproj.github.io/argo-workflows/workflow-pod-security-context/
{"level":"info","ts":1641890461.7947617,"logger":"argo-events.sensor","caller":"sensors/listener.go:376","msg":"successfully processed the trigger","sensorName":"webhook","triggerName":"argo-workflow-trigger","triggerType":"ArgoWorkflow","triggeredBy":["test-dep"],"triggeredByEvents":["33663965323338662d633133322d343935362d393338342d666563653163643438663138"]}
```

**Comment by vfarcic** [comment]
The issue is probably that the request you sent directly does not have the credentials so Workflow is rejecting it thinking that something "fishy" is going on. If that's easier, you can run or re-run workflows directly from the Web UI.

**Comment by nishit93-hub** [comment]
By credentials you mean RBAC rule is not defined properly or other credentials that I am using in the workflow.

**Comment by nishit93-hub** [comment]
Actually, i want to submit an workflow again whenever an event trigger through webook, i don't want to re-submit workflow again.

**Comment by vfarcic** [comment]
I'm not sure I understand. I might be confused with the word "again" in "workflow again". Do you mean something like https://gist.github.com/48f44d3974db698d3127f52b6e7cd0d3?

**Comment by nishit93-hub** [comment]
I have created new Service account to submit my workflow. Below is the Service account

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-deployment
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: superuser
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: superuser-binding
roleRef:
  kind: ClusterRole
  name: superuser
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: User
  name: superuser
#  apiGroup: rbac.authorization.k8s.io
  namespace: argo
- kind: ServiceAccount
  name: dev-deployment
  namespace: argo   
```

**And this is the workflow i submit using above Service account**

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ci-pipeline
spec:
  entrypoint: ci-pipeline-to-automate-build-and-namespace-backup
  volumes:
  - name: jfrog-artifactory-cred
    secret:
      secretName: dockerconfig
  - name: dockefile-and-wordpresscode
  - name: kubeconfig
    secret:
      secretName: kube-config  
  - name: ssh-key
    secret:
      secretName: git-ssh-new
  - name: backupscript
    secret:
      secretName: backup-script
  - name: restorescript
    secret:
      secretName: restore-script           
  templates:
  - name: ci-pipeline-to-automate-build-and-namespace-backup
    dag:
      tasks:
      - name: git-clone-and-build
        template: gitclone-and-docker-image-build
      - name: backup-namespace
        depends: "(git-clone-and-build.Succeeded)"
        template: on-pass
      - name: restore-namespace
        depends: "(git-clone-and-build.Failed)"
        template: on-fail  
  - name: gitclone-and-docker-image-build
    metadata:
    container:
      image: gcr.io/kaniko-project/executor:latest
      command: [/kaniko/executor]
      args:
        - "--context=dir:///wordpress-code-dockerfile"
        - "--destination=nishit2408/argo-imageupdater:3.0"
      volumeMounts:
      - name: jfrog-artifactory-cred
        mountPath: /kaniko/.docker/
      - name: dockefile-and-wordpresscode
        mountPath: /wordpress-code-dockerfile
    initContainers:
    - name: git-clone
      image: bitnami/git
      command: ["/bin/sh", "-c"]
      args: 
      - |
        mkdir /root/.ssh
        cp /ssh-key/id_rsa /root/.ssh
        chmod -R 600 /root/.ssh
        git clone ssh://git@xx.xx.xx.xxx:/home/git/repos/wordpress-code --config core.sshCommand="ssh -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa" /wordpress-code-dockerfile
      volumeMounts:
      - name: dockefile-and-wordpresscode
        mountPath: /wordpress-code-dockerfile
      - name: ssh-key
        mountPath: /ssh-key
  - name: on-pass
    metadata:
    container:
      image: bitnami/git
      command: ["/bin/sh", "-c"]
      args: 
      - |
        bash /backup-file/backup-script.sh
      volumeMounts:
      - name: backupscript
        mountPath: /backup-file
      - name: kubeconfig
        mountPath: /root/.kube                       
  - name: on-fail
    metadata:
    container:
      image: bitnami/git
      command: ["/bin/sh", "-c"]
      args: 
      - |
        bash /restore-file/restore-script.sh
      volumeMounts:
      - name: restorescript
        mountPath: /restore-file 
      - name: kubeconfig
        mountPath: /root/.kube     
```           
So whenever i submit this above worklow using argo . It works fine and pipeline works.

`argo submit argo-workflow-to-automate-backup-new.yaml --serviceaccount dev-deployment -n argo`
---------------------------------------------------------------------------------------------------------------------------------------------------
Now i want to submit same above workflow using Argo events. So whenever sensor listen events through webhook, it should trigger/submit above workflow.

For that i created this Manifest file

```
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: devops-toolkit
  triggers:
    - template:
        name: argo-workflow-trigger
        argoWorkflow:
          group: ""
          version: v1alpha1
          resource: workflows
          operation: submit
          source:
            resource:          
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: ci-pipeline
              spec:
                entrypoint: ci-pipeline-to-automate-build-and-namespace-backup
                volumes:
                - name: jfrog-artifactory-cred
                  secret:
                    secretName: docker-config
                - name: dockefile-and-wordpresscode
                - name: kubeconfig
                  secret:
                    secretName: kube-config  
                - name: ssh-key
                  secret:
                    secretName: git-ssh
                - name: backupscript
                  secret:
                    secretName: backup-script
                - name: restorescript
                  secret:
                    secretName: restore-script           
                templates:
                - name: ci-pipeline-to-automate-build-and-namespace-backup
                  dag:
                    tasks:
                    - name: git-clone-and-build
                      template: gitclone-and-docker-image-build
                    - name: backup-namespace
                      depends: "(git-clone-and-build.Succeeded)"
                      template: on-pass
                    - name: restore-namespace
                      depends: "(git-clone-and-build.Failed)"
                      template: on-fail  
                - name: gitclone-and-docker-image-build
                  metadata:
                  container:
                    image: gcr.io/kaniko-project/executor:latest
                    command: [/kaniko/executor]
                    args:
                      - "--context=dir:///wordpress-code-dockerfile"
                      - "--destination=nishit2408/argo-imageupdater:3.0"
                    volumeMounts:
                    - name: jfrog-artifactory-cred
                      mountPath: /kaniko/.docker/
                    - name: dockefile-and-wordpresscode
                      mountPath: /wordpress-code-dockerfile
                  initContainers:
                  - name: git-clone
                    image: bitnami/git
                    command: ["/bin/sh", "-c"]
                    args: 
                    - |
                      mkdir /root/.ssh
                      cp /ssh-key/id_rsa /root/.ssh
                      chmod -R 600 /root/.ssh
                      git clone ssh://git@xx.xx.xx.xxx:31227/home/git/repos/code2 --config core.sshCommand="ssh -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa" /wordpress-code-dockerfile
                    volumeMounts:
                    - name: dockefile-and-wordpresscode
                      mountPath: /wordpress-code-dockerfile
                    - name: ssh-key
                      mountPath: /ssh-key
                - name: on-pass
                  metadata:
                  container:
                    image: bitnami/git
                    command: ["/bin/sh", "-c"]
                    args: 
                    - |
                      bash /backup-file/backup-script.sh
                    volumeMounts:
                    - name: backupscript
                      mountPath: /backup-file
                    - name: kubeconfig
                      mountPath: /root/.kube                       
                - name: on-fail
                  metadata:
                  container:
                    image: bitnami/git
                    command: ["/bin/sh", "-c"]
                    args: 
                    - |
                      bash /restore-file/restore-script.sh
                    volumeMounts:
                    - name: restorescript
                      mountPath: /restore-file 
                    - name: kubeconfig
                      mountPath: /root/.kube
```
However whenever sensor listen an events, i trigger the above workflow in logs but actually nothing happens.No new workflow submitted.
